import type { Complexity, ExpectedLength } from "../src/auto/judge.js";
import { routeModel } from "../src/auto/judge.js";

export interface TestCase {
  name: string;
  bucket: string;
  messages: Array<{ role: string; content: string }>;
  expectedC: Complexity;
  expectedL: ExpectedLength;
  expectedRoute: string;
}

function r(c: Complexity, l: ExpectedLength) { return routeModel(c, l); }
function u(content: string) { return [{ role: "user", content }]; }
function su(system: string, user: string) { return [{ role: "system", content: system }, { role: "user", content: user }]; }

export const cases: TestCase[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // LOW + SHORT → free (~55 cases)
  // Simple questions, one-liners, lookups, quick fixes
  // ═══════════════════════════════════════════════════════════════════════

  { bucket: "low+S", name: "math addition", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What is 2 + 2?") },
  { bucket: "low+S", name: "greeting", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Hey, how's it going?") },
  { bucket: "low+S", name: "capital city", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What is the capital of Japan?") },
  { bucket: "low+S", name: "acronym REST", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What does REST stand for?") },
  { bucket: "low+S", name: "acronym CRUD", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What does CRUD stand for?") },
  { bucket: "low+S", name: "python reverse", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Write a Python one-liner to reverse a string.") },
  { bucket: "low+S", name: "js ternary", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What's the syntax for a ternary operator in JavaScript?") },
  { bucket: "low+S", name: "type vs interface", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What's the difference between type and interface in TypeScript?") },
  { bucket: "low+S", name: "http status 418", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What does HTTP status code 418 mean?") },
  { bucket: "low+S", name: "git undo commit", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How do I undo the last git commit without losing changes?") },
  { bucket: "low+S", name: "npm vs yarn", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Should I use npm or yarn? Quick answer.") },
  { bucket: "low+S", name: "null vs undefined", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What's the difference between null and undefined in JavaScript?") },
  { bucket: "low+S", name: "chmod 755", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What does chmod 755 do?") },
  { bucket: "low+S", name: "env var node", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How do I read an environment variable in Node.js?") },
  { bucket: "low+S", name: "array flat", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How do I flatten a nested array in JavaScript?") },
  { bucket: "low+S", name: "fix CORS", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("My Express API returns a CORS error from localhost:3000. Quick fix?") },
  { bucket: "low+S", name: "debug undefined map", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Getting 'Cannot read properties of undefined (reading map)'. How to fix?") },
  { bucket: "low+S", name: "json parse error", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("SyntaxError: Unexpected token < in JSON at position 0 — what causes this?") },
  { bucket: "low+S", name: "port in use", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("EADDRINUSE port 3000. How do I kill the process using it?") },
  { bucket: "low+S", name: "date format js", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Format a Date as YYYY-MM-DD in JavaScript without libraries.") },
  { bucket: "low+S", name: "sleep js", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How to make a sleep/delay function in JavaScript?") },
  { bucket: "low+S", name: "deep clone", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Best way to deep clone an object in JavaScript?") },
  { bucket: "low+S", name: "uuid generate", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Generate a UUID v4 in Node.js.") },
  { bucket: "low+S", name: "regex email", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Give me a regex to validate email addresses.") },
  { bucket: "low+S", name: "convert cm inches", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How many centimeters in 5 inches?") },
  { bucket: "low+S", name: "translate hello jp", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How do you say 'hello' in Japanese?") },
  { bucket: "low+S", name: "boolean ts check", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Is TypeScript a superset of JavaScript?") },
  { bucket: "low+S", name: "css center div", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How to center a div horizontally and vertically with CSS?") },
  { bucket: "low+S", name: "docker stop all", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Command to stop all running Docker containers?") },
  { bucket: "low+S", name: "git stash pop", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What's the difference between git stash pop and git stash apply?") },
  { bucket: "low+S", name: "promise all vs race", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Difference between Promise.all and Promise.race?") },
  { bucket: "low+S", name: "bash find files", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Find all .ts files in current directory recursively. Bash command.") },
  { bucket: "low+S", name: "python list comp", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Write a Python list comprehension to get even numbers from 1 to 100.") },
  { bucket: "low+S", name: "sql count rows", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("SQL query to count rows in a table where status is 'active'?") },
  { bucket: "low+S", name: "go hello world", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Hello world in Go.") },
  { bucket: "low+S", name: "rust ownership", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Explain Rust ownership in one paragraph.") },
  { bucket: "low+S", name: "map vs forEach", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("When should I use map vs forEach in JavaScript?") },
  { bucket: "low+S", name: "what is jsx", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What is JSX?") },
  { bucket: "low+S", name: "package-lock purpose", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Should I commit package-lock.json?") },
  { bucket: "low+S", name: "optional chaining", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How does optional chaining (?.) work in JavaScript?") },
  { bucket: "low+S", name: "string to number", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Best way to convert a string to a number in TypeScript?") },
  { bucket: "low+S", name: "sql join types", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What's the difference between INNER JOIN and LEFT JOIN?") },
  { bucket: "low+S", name: "what is WASM", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("What is WebAssembly in one sentence?") },
  { bucket: "low+S", name: "how to exit vim", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How do I exit vim?") },
  { bucket: "low+S", name: "ts readonly", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("How does Readonly<T> work in TypeScript?") },

  // ═══════════════════════════════════════════════════════════════════════
  // LOW + LONG → free (~35 cases)
  // Explanations, single class/function, tutorials, comparisons
  // ═══════════════════════════════════════════════════════════════════════

  { bucket: "low+L", name: "explain OAuth flow", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain the OAuth 2.0 authorization code flow step by step with diagrams in text.") },
  { bucket: "low+L", name: "priority queue class", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Write a TypeScript class for a priority queue with insert, extractMin, and peek. Use a min-heap.") },
  { bucket: "low+L", name: "redis vs memcached", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Compare Redis vs Memcached for session caching. Detailed pros/cons and when to use each.") },
  { bucket: "low+L", name: "closures explained", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain JavaScript closures with 3 practical examples and common pitfalls.") },
  { bucket: "low+L", name: "git rebase vs merge", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain Git rebase vs merge workflow with examples. When to use each?") },
  { bucket: "low+L", name: "linked list ts", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Implement a doubly linked list in TypeScript with insert, delete, find, and reverse methods.") },
  { bucket: "low+L", name: "debounce throttle", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Write TypeScript implementations of both debounce and throttle with full types. Explain the difference.") },
  { bucket: "low+L", name: "docker compose app", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Write a docker-compose.yml for a Node.js app with PostgreSQL, Redis, and nginx reverse proxy. Explain each service.") },
  { bucket: "low+L", name: "event loop explain", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain the Node.js event loop in detail: phases, microtasks, macrotasks, with code examples.") },
  { bucket: "low+L", name: "sql joins tutorial", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Tutorial on SQL joins: INNER, LEFT, RIGHT, FULL, CROSS. Give example tables and queries for each.") },
  { bucket: "low+L", name: "promise patterns", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Show me all the Promise patterns in JavaScript: all, allSettled, race, any, chaining, error handling. With examples.") },
  { bucket: "low+L", name: "binary search tree", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Implement a binary search tree in TypeScript with insert, search, delete, and in-order traversal.") },
  { bucket: "low+L", name: "REST best practices", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("List REST API design best practices with examples: naming, versioning, pagination, error handling, status codes.") },
  { bucket: "low+L", name: "react hooks tutorial", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain all the built-in React hooks with practical examples: useState, useEffect, useContext, useRef, useMemo, useCallback, useReducer.") },
  { bucket: "low+L", name: "nginx config", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Write an nginx config for reverse proxying to a Node.js app with SSL, gzip, rate limiting, and WebSocket support. Explain each block.") },
  { bucket: "low+L", name: "graph algorithms", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Implement BFS and DFS in TypeScript for a graph represented as an adjacency list. Include both iterative and recursive versions.") },
  { bucket: "low+L", name: "testing patterns", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Write a Jest test suite for a parseDate(str: string): Date function that handles ISO 8601, Unix timestamps, and relative dates.") },
  { bucket: "low+L", name: "typescript generics", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain TypeScript generics from basics to advanced: constraints, conditional types, infer, mapped types. With examples for each.") },
  { bucket: "low+L", name: "design patterns js", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Show me the Observer, Strategy, and Factory patterns implemented in TypeScript with practical examples.") },
  { bucket: "low+L", name: "LRU cache impl", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Implement an LRU cache in TypeScript with O(1) get and put. Use a doubly linked list + hashmap.") },
  { bucket: "low+L", name: "websocket basics", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain WebSockets: how they work, the handshake, frames, and write a basic Node.js WebSocket server and client.") },
  { bucket: "low+L", name: "css grid tutorial", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("CSS Grid tutorial: explain grid-template-rows/columns, areas, auto-fill, minmax, and fr units. Include 5 layout examples.") },
  { bucket: "low+L", name: "regex deep dive", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Write regexes for: email validation, URL parsing, phone numbers, dates, and IP addresses. Explain each pattern part by part.") },
  { bucket: "low+L", name: "protobuf vs json", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Compare Protobuf vs JSON for API communication: performance benchmarks, schema evolution, tooling, and when to use each.") },
  { bucket: "low+L", name: "sorting algorithms", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Implement quicksort, mergesort, and heapsort in TypeScript. Show time/space complexity analysis for each.") },
  { bucket: "low+L", name: "express middleware", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain Express.js middleware in depth: how the chain works, error middleware, router-level vs app-level, with 5 practical examples.") },
  { bucket: "low+L", name: "postgres indexes", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain PostgreSQL index types: B-tree, Hash, GIN, GiST, BRIN. When to use each, with example queries and CREATE INDEX statements.") },
  { bucket: "low+L", name: "async iterators", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain async iterators and generators in JavaScript: for-await-of, Symbol.asyncIterator, practical streaming examples.") },
  { bucket: "low+L", name: "trie implementation", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Implement a Trie in TypeScript with insert, search, startsWith, autocomplete, and delete. Include usage examples.") },
  { bucket: "low+L", name: "solid principles", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain SOLID principles with TypeScript code examples for each. Show the bad code and how to refactor it.") },

  // ═══════════════════════════════════════════════════════════════════════
  // HARD + SHORT → free (~25 cases)
  // Strategic decisions, architecture recommendations, plans (not code)
  // ═══════════════════════════════════════════════════════════════════════

  { bucket: "hard+S", name: "refactor strategy", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: su("You are a senior engineer.", "Our auth middleware uses callbacks and 12 route handlers depend on it. What's the safest strategy to migrate to async/await? Just the plan, no code.") },
  { bucket: "hard+S", name: "CI/CD tool pick", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Monorepo with 5 packages, deploying to AWS ECS. Turborepo vs Nx vs Bazel? Recommendation with tradeoffs, no implementation.") },
  { bucket: "hard+S", name: "schema review JSONB", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("We're storing user preferences as JSONB in the users table (2M users, read every request). Separate table vs JSONB column — tradeoffs?") },
  { bucket: "hard+S", name: "cache invalidation", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Our Redis cache gets stale data after DB writes. What cache invalidation strategy should we use? Write-through vs write-behind vs event-driven? Just the recommendation.") },
  { bucket: "hard+S", name: "queue selection", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("RabbitMQ vs Kafka vs SQS for our use case: 50k events/sec, need ordering within a partition, must handle replay. Which and why? No code.") },
  { bucket: "hard+S", name: "test strategy", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: su("Senior QA engineer.", "Our API has 200 endpoints but only 30% test coverage. What's the most efficient strategy to get to 80%? Prioritization framework only.") },
  { bucket: "hard+S", name: "deployment strategy", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Blue-green vs canary vs rolling deploys for our microservices on K8s. We have 15 services, some stateful. Recommendation?") },
  { bucket: "hard+S", name: "DB migration approach", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("We need to split our monolithic PostgreSQL into separate databases per microservice. Zero-downtime approach? Strategy only.") },
  { bucket: "hard+S", name: "API versioning", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("URL path vs header vs query param for API versioning? We have 50 clients, 10 breaking changes/year. What approach and why?") },
  { bucket: "hard+S", name: "logging architecture", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Structured logging for a microservices arch with 20 services. ELK vs Loki+Grafana vs Datadog? We're on AWS, budget-conscious.") },
  { bucket: "hard+S", name: "state management pick", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("React app with complex form state, real-time updates via WebSocket, and offline support. Redux vs Zustand vs Jotai? Recommendation.") },
  { bucket: "hard+S", name: "auth strategy", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Session-based vs JWT vs OAuth2+OIDC for a B2B SaaS with SSO requirements and API access. Which approach and why? Just the architecture decision.") },
  { bucket: "hard+S", name: "data model review", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: su("Database architect.", "We chose event sourcing for our order system but reads are getting slow. Should we switch to CQRS, add projections, or go back to CRUD? Pros/cons of each for our case.") },
  { bucket: "hard+S", name: "migration framework", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Moving from REST to GraphQL incrementally. What migration strategy avoids breaking existing clients? High-level plan only.") },
  { bucket: "hard+S", name: "scaling bottleneck", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Our Node.js API handles 1000 req/sec but CPU spikes to 100% at 1500. Should we add workers, switch to Go, or optimize the hot path? Analysis only.") },
  { bucket: "hard+S", name: "mono vs poly repo", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("5 teams, 12 services, shared proto definitions. Monorepo vs polyrepo? We currently have polyrepo but dependency management is painful.") },
  { bucket: "hard+S", name: "error handling strategy", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Our microservices have inconsistent error handling. Some throw, some return Result types, some use error middleware. How should we standardize? Architecture recommendation.") },
  { bucket: "hard+S", name: "search infra pick", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Full-text search over 10M documents, need fuzzy matching and faceted search. Elasticsearch vs Meilisearch vs Typesense? Budget matters.") },
  { bucket: "hard+S", name: "real-time arch", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Need real-time notifications for 100k concurrent users. WebSockets vs SSE vs long polling? We're behind a load balancer on AWS.") },
  { bucket: "hard+S", name: "API gateway choice", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Kong vs AWS API Gateway vs custom Node.js gateway for 20 microservices. Need rate limiting, auth, and request transformation. Which?") },
  { bucket: "hard+S", name: "feature flag arch", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Want to implement feature flags. LaunchDarkly vs Unleash vs custom solution? 50 devs, 10 deploys/day. Recommendation.") },
  { bucket: "hard+S", name: "ORM vs raw SQL", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Prisma vs Drizzle vs raw SQL with pg for a new TypeScript project? We have complex queries with CTEs and window functions.") },
  { bucket: "hard+S", name: "container orchestration", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("ECS vs EKS vs Fargate for a team of 5 running 8 services? We don't have a dedicated DevOps person. Simplicity matters.") },

  // ═══════════════════════════════════════════════════════════════════════
  // HARD + LONG → sonnet (~35 cases)
  // Multi-file implementations, full features with tests
  // ═══════════════════════════════════════════════════════════════════════

  { bucket: "hard+L", name: "REST API + tests", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a complete REST API for a todo app with Express: CRUD endpoints, Zod validation, error middleware, and integration tests with supertest. All files.") },
  { bucket: "hard+L", name: "CLI watcher tool", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a CLI tool in TypeScript that watches a directory for changes, debounces events, and syncs to a remote via SSH. Include arg parsing, config file, and graceful shutdown.") },
  { bucket: "hard+L", name: "JWT auth system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Implement JWT auth for Express: login/register, protected routes middleware, refresh token rotation, password hashing, rate limiting. Include DB schema and all route files.") },
  { bucket: "hard+L", name: "WebSocket chat full", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a real-time chat system: WebSocket server with rooms, auth, message history from DB, typing indicators, and a React client with reconnection.") },
  { bucket: "hard+L", name: "plugin system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Implement a plugin system for Node.js: plugin interface, lifecycle hooks (init/start/stop), dependency resolution, config validation, and directory-based discovery.") },
  { bucket: "hard+L", name: "React data table", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a complete React data table: server-side pagination, column sorting, filtering, row selection, CSV export. Component, hooks, types, mock API.") },
  { bucket: "hard+L", name: "CI/CD pipeline", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Design a complete GitHub Actions CI/CD pipeline for a monorepo: per-package test on changes, Docker builds, staging on PR merge, prod on release tag, rollback, Slack notifications.") },
  { bucket: "hard+L", name: "GraphQL API", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a GraphQL API with Apollo Server for a blog: posts, comments, users. Include resolvers, type definitions, auth middleware, pagination, and dataloader for N+1 prevention.") },
  { bucket: "hard+L", name: "job queue system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a job queue system in Node.js with Redis: job scheduling, retries with exponential backoff, dead letter queue, concurrency control, and a dashboard API to monitor jobs.") },
  { bucket: "hard+L", name: "form builder", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a dynamic form builder in React: schema-driven rendering, conditional fields, validation with Zod, multi-step forms, and JSON schema import/export.") },
  { bucket: "hard+L", name: "file upload service", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a file upload service: multipart upload, chunk resumption, virus scanning hook, S3 storage, presigned URLs, and a React upload component with progress.") },
  { bucket: "hard+L", name: "rate limiter middleware", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Implement rate limiting middleware for Express: sliding window with Redis, per-user and per-IP limits, configurable rules, retry-after headers, and unit tests.") },
  { bucket: "hard+L", name: "email service", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build an email notification service: template rendering with MJML, queue processing with BullMQ, delivery tracking, bounce handling, and an admin API.") },
  { bucket: "hard+L", name: "search API", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a search API with Elasticsearch: indexing pipeline, full-text search, faceted filtering, autocomplete suggestions, and relevance tuning. Include the index mappings and query builders.") },
  { bucket: "hard+L", name: "RBAC system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Implement a role-based access control system: roles, permissions, resource-level policies, middleware for Express, admin API for role management, and the database schema.") },
  { bucket: "hard+L", name: "migration tool", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a database migration tool in TypeScript: migration file generation, up/down execution, locking to prevent concurrent runs, dry-run mode, and status tracking.") },
  { bucket: "hard+L", name: "webhook system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a webhook delivery system: registration API, payload signing (HMAC), retry with backoff, delivery logging, and a React dashboard to manage subscriptions.") },
  { bucket: "hard+L", name: "caching layer", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a multi-tier caching layer for an API: in-memory L1, Redis L2, cache-aside pattern, TTL management, cache warming, invalidation via pub/sub, and metrics.") },
  { bucket: "hard+L", name: "SSR React app", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a server-side rendered React app from scratch (no Next.js): Express server, hydration, data fetching, code splitting, and a router. All files.") },
  { bucket: "hard+L", name: "API client SDK", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a TypeScript SDK for a REST API: typed methods for each endpoint, automatic retry, auth token refresh, request/response interceptors, pagination helpers, and comprehensive types.") },
  { bucket: "hard+L", name: "notification system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a notification system: in-app, email, and push channels. Include a preference system, batching/digest, read tracking, and the React notification center component.") },
  { bucket: "hard+L", name: "audit log service", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build an audit logging service: capture middleware for Express, structured event storage, search/filter API, retention policies, and an audit trail viewer component.") },
  { bucket: "hard+L", name: "feature flag impl", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a feature flag system: flag evaluation engine, percentage rollouts, user targeting rules, an admin API, React provider/hook, and the database schema.") },
  { bucket: "hard+L", name: "health check system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a health check system for microservices: deep health checks (DB, Redis, external APIs), dependency graph, circuit breaker integration, Prometheus metrics, and a status page API.") },
  { bucket: "hard+L", name: "i18n system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build an internationalization system: message extraction, plural rules, ICU message format, React components/hooks, lazy loading of locales, and a translation management API.") },

  // ═══════════════════════════════════════════════════════════════════════
  // EXTREME + SHORT → sonnet (~20 cases)
  // Deep expertise, architecture decisions, but focused/concise output
  // ═══════════════════════════════════════════════════════════════════════

  { bucket: "extr+S", name: "rate limit algo", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Design a distributed rate limiting algorithm for multiple data centers with eventual consistency. Core algorithm and consistency model only, not the full implementation.") },
  { bucket: "extr+S", name: "CRDT vs OT pick", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Building a collaborative editor: 50 concurrent editors, rich text, offline support. CRDTs vs OT? Architecture recommendation with reasoning, not implementation.") },
  { bucket: "extr+S", name: "service boundaries", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: su("Reviewing a 50k LOC Express monolith.", "Identify bounded contexts and propose service boundaries. Just boundaries and communication patterns, not the migration plan.") },
  { bucket: "extr+S", name: "consensus pick", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Distributed KV store: 5 nodes, strong consistency, ~10k writes/sec. Raft vs Paxos vs EPaxos? Which and why?") },
  { bucket: "extr+S", name: "CAP theorem app", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our multi-region database needs to handle network partitions. Analyze our options through the CAP theorem lens. We currently use single-leader Postgres replication.") },
  { bucket: "extr+S", name: "isolation levels", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("We're seeing phantom reads in our payment system. Analyze which transaction isolation level we need and the performance tradeoffs. We use PostgreSQL.") },
  { bucket: "extr+S", name: "sharding strategy", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our single PostgreSQL instance handles 500M rows and is hitting limits. Analyze sharding strategies: range vs hash vs directory-based. What's right for a multi-tenant SaaS?") },
  { bucket: "extr+S", name: "vector clock design", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Design the conflict resolution strategy for our distributed shopping cart using vector clocks. How do we handle concurrent updates across regions? Just the algorithm.") },
  { bucket: "extr+S", name: "GC tuning analysis", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our JVM service has 200ms GC pauses at p99. Running G1GC on 32GB heap. Analyze: should we tune G1, switch to ZGC, or reduce object allocation? Diagnosis framework.") },
  { bucket: "extr+S", name: "zero-downtime migration", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("We need to change a primary key type from INT to UUID across 50 tables with foreign keys. Design a zero-downtime migration strategy. High-level plan only.") },
  { bucket: "extr+S", name: "event sourcing audit", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our event-sourced system has 2B events and rebuilding projections takes 6 hours. Analyze: snapshots vs parallel projection vs switching to hybrid CQRS. Recommendation.") },
  { bucket: "extr+S", name: "TLS handshake perf", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our API's p99 latency jumps from 50ms to 400ms for new connections due to TLS handshake. Analyze: session resumption, TLS 1.3, 0-RTT, connection pooling. What's the right fix?") },
  { bucket: "extr+S", name: "bloom filter design", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Design a distributed bloom filter for deduplication across 10 services processing 1M events/sec. Size calculations, false positive rate analysis, and sync strategy.") },
  { bucket: "extr+S", name: "linearizability check", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Is our distributed lock implementation linearizable? We use Redis SETNX with TTL and Lua scripts for CAS. Analyze the edge cases and potential violations.") },
  { bucket: "extr+S", name: "cache coherence", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Multi-region cache coherence: we have Redis clusters in 3 regions and see stale reads after writes. Analyze consistency options: invalidation vs replication vs CRDTs for cache.") },
  { bucket: "extr+S", name: "backpressure design", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our streaming pipeline drops events under load. Design a backpressure mechanism for a Kafka→processor→DB pipeline. Just the flow control strategy, not implementation.") },

  // ═══════════════════════════════════════════════════════════════════════
  // EXTREME + LONG → opus (~30 cases)
  // Full system designs, comprehensive audits, research-grade output
  // ═══════════════════════════════════════════════════════════════════════

  { bucket: "extr+L", name: "dist rate limiter FULL", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design a distributed rate limiter service across multiple data centers. Architecture, data structures, consistency model, failure modes, core algorithm code, API layer, Redis cluster + local fallback, and monitoring.") },
  { bucket: "extr+L", name: "collab editor FULL", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design a real-time collaborative document editor like Google Docs. CRDT vs OT analysis, WebSocket architecture, conflict resolution, persistence, auth, and TypeScript code for the core sync engine.") },
  { bucket: "extr+L", name: "monolith migration FULL", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: su("Senior architect reviewing a 50k LOC Express monolith.", "Create a complete migration plan: bounded contexts, service boundaries, data migration, inter-service communication, phased rollout with rollback procedures.") },
  { bucket: "extr+L", name: "security audit FULL", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Comprehensive security audit of a REST API: auth flaws, injection, rate limiting, CORS, dependency vulns, and remediation plan with code for each issue.") },
  { bucket: "extr+L", name: "SaaS DB FULL", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design a complete multi-tenant SaaS database: row-level security, audit logging, soft deletes, full-text search, real-time subscriptions, migrations, indexes, and TypeScript ORM layer.") },
  { bucket: "extr+L", name: "ML pipeline FULL", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("End-to-end ML pipeline for fraud detection: preprocessing, feature engineering, training with cross-validation, hyperparameter tuning, serving API, A/B testing, monitoring. Python code for each component.") },
  { bucket: "extr+L", name: "consensus comparison", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Comprehensive analysis of consensus algorithms: Raft, Paxos, PBFT, HotStuff. Theoretical foundations, performance, fault tolerance, real-world implementations, and pseudocode for each.") },
  { bucket: "extr+L", name: "compiler full", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a complete lexer, parser, and tree-walking interpreter for a language with variables, functions, if/else, while, arithmetic. TypeScript, proper AST, error recovery.") },
  { bucket: "extr+L", name: "K8s operator", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a Kubernetes operator for managing database clusters: CRD definitions, controller logic, automated failover, backup scheduling, scaling, status reporting. Include Go code for the reconciliation loop.") },
  { bucket: "extr+L", name: "event-driven arch", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design a complete event-driven architecture for an e-commerce platform: event schemas, saga orchestration for order processing, exactly-once delivery, dead letter handling, event store, and the complete TypeScript implementation of the saga engine.") },
  { bucket: "extr+L", name: "observability platform", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design a complete observability platform: distributed tracing (OpenTelemetry), metrics aggregation, log correlation, alerting rules engine, SLO tracking, and a dashboard API. Include the collector pipeline, storage layer, and query engine code.") },
  { bucket: "extr+L", name: "API gateway full", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a complete API gateway from scratch: request routing, authentication, rate limiting, circuit breaker, request/response transformation, logging, metrics, and plugin system. Include all TypeScript code and configuration schema.") },
  { bucket: "extr+L", name: "search engine", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a text search engine from scratch: inverted index, TF-IDF scoring, tokenization pipeline, boolean queries, phrase search, fuzzy matching, and a HTTP API. Include all the data structures and algorithms in TypeScript.") },
  { bucket: "extr+L", name: "OAuth2 server", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Implement a complete OAuth2 authorization server: authorization code, PKCE, client credentials, refresh tokens, token introspection, JWK management, consent screen, and OIDC discovery. Include all endpoints and the token store.") },
  { bucket: "extr+L", name: "load balancer", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design and implement a Layer 7 load balancer: HTTP/2 support, health checking, multiple algorithms (round-robin, least-connections, consistent hashing), connection draining, dynamic config reload. Include the core routing engine code.") },
  { bucket: "extr+L", name: "database engine", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a simple database storage engine: B+ tree index, WAL for durability, buffer pool, basic SQL parser (SELECT/INSERT/WHERE), MVCC for concurrency. Include all TypeScript code.") },
  { bucket: "extr+L", name: "CDC pipeline", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design a complete Change Data Capture pipeline: WAL parsing, event transformation, schema registry, exactly-once delivery to multiple consumers, backfill support, and monitoring. Include the architecture, data flow, and core processor code.") },
  { bucket: "extr+L", name: "workflow engine", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a workflow execution engine like Temporal: workflow definitions, activity execution, retry policies, timers, compensation (saga), state persistence, and a worker framework. Include the core execution engine in TypeScript.") },
  { bucket: "extr+L", name: "perf audit full", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Comprehensive performance audit of a Node.js API: profiling methodology, common bottlenecks (event loop blocking, memory leaks, connection pools), database query optimization, caching strategy, CDN configuration, and load testing framework. Code examples for each fix.") },
  { bucket: "extr+L", name: "distributed tracing", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Implement a distributed tracing system from scratch: span collection, trace propagation (W3C Trace Context), sampling strategies, storage backend, query API for trace reconstruction, and a flame graph visualization endpoint. Include all code.") },
  { bucket: "extr+L", name: "type system impl", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Implement a Hindley-Milner type inference system in TypeScript: type variables, unification, let-polymorphism, recursive types, and a constraint solver. Include the AST, type checker, and examples.") },
  { bucket: "extr+L", name: "container runtime", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a minimal container runtime: namespace isolation (PID, NET, MNT), cgroup resource limits, overlay filesystem, image pulling/unpacking, and a CLI interface. Include all the Linux syscall wrappers and orchestration code.") },
  { bucket: "extr+L", name: "CRDT library", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a CRDT library: implement G-Counter, PN-Counter, LWW-Register, OR-Set, and a JSON CRDT document type. Include merge functions, serialization, and a sync protocol over WebSocket. Full TypeScript implementation.") },
  { bucket: "extr+L", name: "service mesh", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design a service mesh sidecar proxy: mTLS between services, circuit breaking, retry policies, load balancing, traffic splitting for canary deploys, and observability integration. Include the proxy architecture and core request handling code.") },

  // ─── EXTRA: pad to 200 ──────────────────────────────────────────────

  // low+S extras
  { bucket: "low+S", name: "var vs let vs const", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("When should I use var vs let vs const in JavaScript?") },
  { bucket: "low+S", name: "check array empty", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Best way to check if an array is empty in TypeScript?") },
  { bucket: "low+S", name: "python f-string", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Show me Python f-string formatting with padding and decimal places.") },
  { bucket: "low+S", name: "postgres create user", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("SQL command to create a user with a password in PostgreSQL?") },
  { bucket: "low+S", name: "bash pipe count", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Bash command to count number of lines in a file?") },

  // low+L extras
  { bucket: "low+L", name: "state machines ts", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Implement a finite state machine in TypeScript with typed transitions, guards, and event handling. Show a traffic light example.") },
  { bucket: "low+L", name: "JWT explained", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain JWTs in depth: structure, signing algorithms (HS256 vs RS256), claims, refresh patterns, and security pitfalls. With code examples.") },
  { bucket: "low+L", name: "streams node", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Explain Node.js streams: readable, writable, duplex, transform. Show practical examples: file processing, HTTP streaming, piping.") },
  { bucket: "low+L", name: "docker multi-stage", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Write a multi-stage Dockerfile for a TypeScript Node.js app: build stage, test stage, production stage. Explain each stage and optimization.") },
  { bucket: "low+L", name: "sql window functions", expectedC: "low", expectedL: "long", expectedRoute: r("low","long"),
    messages: u("Tutorial on SQL window functions: ROW_NUMBER, RANK, DENSE_RANK, LAG, LEAD, SUM OVER. Include example queries with output.") },

  // hard+S extras
  { bucket: "hard+S", name: "session vs JWT arch", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("For a banking app with strict security: session cookies vs JWT? Consider XSS, CSRF, revocation, and regulatory requirements. Architecture decision only.") },
  { bucket: "hard+S", name: "multi-region DB", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Active-active vs active-passive for our multi-region PostgreSQL setup. We have users in US, EU, Asia. Latency matters but consistency matters more. Recommendation?") },

  // hard+L extras
  { bucket: "hard+L", name: "config management", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a configuration management system: hierarchical configs (default→env→service), hot reload via file watch or API, typed config validation with Zod, secrets integration, and change audit logging.") },
  { bucket: "hard+L", name: "task scheduler", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a cron-like task scheduler in Node.js: cron expression parsing, task registration, distributed locking to prevent duplicates, execution logging, retry with backoff, and a management API.") },
  { bucket: "hard+L", name: "API test framework", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build an API testing framework: test definition DSL, environment management, request chaining with variable extraction, assertions, parallel execution, HTML report generation.") },
  { bucket: "hard+L", name: "PDF generator", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a PDF generation service: HTML/CSS template rendering, dynamic data binding, header/footer/page numbers, table of contents, batch generation queue, and a REST API.") },
  { bucket: "hard+L", name: "multitenancy layer", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a multi-tenancy layer for an Express app: tenant resolution from subdomain/header, schema-per-tenant with Postgres schemas, connection pooling, tenant provisioning API, and middleware.") },
  { bucket: "hard+L", name: "SSO integration", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Implement SAML SSO integration for a SaaS app: SP metadata, assertion consumer service, attribute mapping, session management, and SCIM provisioning. Include all route handlers and the SAML processing logic.") },
  { bucket: "hard+L", name: "AB testing system", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build an A/B testing system: experiment definition, user bucketing (deterministic hashing), exposure logging, statistical significance calculator, and a React dashboard for results.") },
  { bucket: "hard+L", name: "content pipeline", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a content processing pipeline: markdown parsing, syntax highlighting, image optimization, link checking, TOC generation, and an incremental build system. TypeScript with plugins.") },
  { bucket: "hard+L", name: "API mocking server", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a programmable API mock server: route matching with patterns, dynamic response generation, request recording/playback, proxy mode with recording, and a config hot-reload system.") },
  { bucket: "hard+L", name: "permissions engine", expectedC: "hard", expectedL: "long", expectedRoute: r("hard","long"),
    messages: u("Build a fine-grained permissions engine like Google Zanzibar: relation tuples, check/expand/lookup APIs, namespace configuration, and a Postgres-backed store. Include the evaluation engine code.") },

  // extr+S extras
  { bucket: "extr+S", name: "write amplification", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our LSM-tree based storage has 40x write amplification. Analyze: tiered vs leveled compaction, bloom filter tuning, and optimal level ratios. Diagnosis only.") },
  { bucket: "extr+S", name: "tail latency analysis", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our p99 is 10x our p50 for database reads. Analyze root causes: connection pool contention, query plan instability, buffer pool misses, or checkpoint storms. Diagnosis framework.") },
  { bucket: "extr+S", name: "gossip protocol pick", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Membership protocol for our distributed cache cluster: SWIM vs traditional gossip vs HyParView. 500 nodes, need fast failure detection (<2s). Which and why?") },
  { bucket: "extr+S", name: "memory model analysis", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Analyze the memory ordering guarantees we need for our lock-free queue implementation. Compare acquire-release vs sequential consistency. What's the minimum we can get away with?") },

  // extr+L extras
  { bucket: "extr+L", name: "query optimizer", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a SQL query optimizer: parse SQL to AST, generate logical plan, apply optimization rules (predicate pushdown, join reordering), cost model, and generate physical execution plan. Include all TypeScript code.") },
  { bucket: "extr+L", name: "raft implementation", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Implement the Raft consensus algorithm: leader election, log replication, safety, cluster membership changes, log compaction. Include the complete state machine, RPC handlers, and test harness in TypeScript.") },
  { bucket: "extr+L", name: "network simulator", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a network partition simulator for testing distributed systems: programmable network conditions (latency, drops, partitions), deterministic execution, a scheduler, and integration with a simple KV store to demonstrate. Full TypeScript implementation.") },
  { bucket: "extr+L", name: "LSM tree engine", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Implement an LSM-tree storage engine: memtable (skip list), SSTable format, compaction (leveled), bloom filters, block cache, range scans, and a simple key-value API. Include all data structures and I/O code in TypeScript.") },
  { bucket: "extr+L", name: "autoscaler design", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Design and implement a custom autoscaler for Kubernetes: custom metrics collection, scaling policies (target-based, schedule-based, predictive), cooldown management, and integration with HPA. Include the controller code, CRDs, and the prediction model.") },
  { bucket: "extr+L", name: "GraphQL engine", expectedC: "extreme", expectedL: "long", expectedRoute: r("extreme","long"),
    messages: u("Build a GraphQL execution engine from scratch: schema parsing, query validation, resolver execution, dataloader integration, subscription support via WebSocket, and query complexity analysis. Complete TypeScript implementation.") },
  // final 4
  { bucket: "low+S", name: "ts enum vs union", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Enum vs union type in TypeScript? Which is better?") },
  { bucket: "low+S", name: "what is CORS", expectedC: "low", expectedL: "short", expectedRoute: r("low","short"),
    messages: u("Explain CORS in one paragraph.") },
  { bucket: "hard+S", name: "CDN invalidation", expectedC: "hard", expectedL: "short", expectedRoute: r("hard","short"),
    messages: u("Our CDN serves stale content after deploys. Cache busting via file hashing vs CDN invalidation API vs versioned URLs? Tradeoffs for a React SPA.") },
  { bucket: "extr+S", name: "NUMA-aware design", expectedC: "extreme", expectedL: "short", expectedRoute: r("extreme","short"),
    messages: u("Our in-memory database runs on a 2-socket NUMA system and we see 30% perf degradation from remote memory access. Analyze NUMA-aware allocation strategies. Recommendation only.") },
];

if (cases.length !== 200) {
  console.warn(`WARNING: Expected 200 cases, got ${cases.length}`);
}
